spring:
  application:
    name: microblog
logging:
  level:
    org:
      springframework: DEBUG

server:
  port: 8081
  context-path: /microblog

security:
  basic:
    enabled: false
  oauth2:
    resource:
      id: microblog
      token-info-uri: http://localhost:8080/uc/oauth/check_token
    client:
      client-id: microblog
      client-secret: secret123

